resources:
  - ../../base

namespace: todo-app
commonLabels:
  env: staging

images:
  - name: khhini/todo-app-api
    newTag: rust-v1.0.0

configMapGenerator:
  - name: todo-app-api-config
    literals:
      - LISTENER.HOST=0.0.0.0
      - LISTENER.PORT=8080

patches:
  - target:
      kind: Deployment
      name: todo-app-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2