apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-api
  template:
    metadata:
      labels:
        app: todo-app-api
    spec:
      containers:
        - name: todo-app-api
          image: asia-southeast2-docker.pkg.dev/khhini-argocd-gitops-exp/khhini-dev/todo-app-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: LISTENER.HOST
              valueFrom:
                configMapKeyRef:
                  key: LISTENER.HOST
                  name: todo-app-api-config
            - name: LISTENER.PORT
              valueFrom:
                configMapKeyRef:
                  key: LISTENER.PORT
                  name: todo-app-api-config